/**
 * Semantic mapping dictionary for Technology and Brand Icons.
 * Maps natural language terms, aliases, abbreviations, and common variants
 * to their canonical @thesvg/icons slug.
 */

export interface SemanticIconEntry {
  slug: string;
  category: "language" | "framework" | "database" | "cloud" | "devtool" | "saas" | "security" | "protocol" | "general";
  displayName: string;
}

export const SEMANTIC_ICON_MAP: Record<string, SemanticIconEntry> = {
  // Programming Languages
  python: { slug: "python", category: "language", displayName: "Python" },
  py: { slug: "python", category: "language", displayName: "Python" },
  python3: { slug: "python", category: "language", displayName: "Python" },
  typescript: { slug: "typescript", category: "language", displayName: "TypeScript" },
  ts: { slug: "typescript", category: "language", displayName: "TypeScript" },
  javascript: { slug: "javascript", category: "language", displayName: "JavaScript" },
  js: { slug: "javascript", category: "language", displayName: "JavaScript" },
  es6: { slug: "javascript", category: "language", displayName: "JavaScript" },
  go: { slug: "go", category: "language", displayName: "Go" },
  golang: { slug: "go", category: "language", displayName: "Go" },
  rust: { slug: "rust", category: "language", displayName: "Rust" },
  rustlang: { slug: "rust", category: "language", displayName: "Rust" },
  java: { slug: "java", category: "language", displayName: "Java" },
  jdk: { slug: "java", category: "language", displayName: "Java" },
  php: { slug: "php", category: "language", displayName: "PHP" },
  ruby: { slug: "ruby", category: "language", displayName: "Ruby" },
  c: { slug: "c", category: "language", displayName: "C" },
  cpp: { slug: "cplusplus", category: "language", displayName: "C++" },
  cplusplus: { slug: "cplusplus", category: "language", displayName: "C++" },
  "c++": { slug: "cplusplus", category: "language", displayName: "C++" },
  csharp: { slug: "csharp", category: "language", displayName: "C#" },
  "c#": { slug: "csharp", category: "language", displayName: "C#" },
  swift: { slug: "swift", category: "language", displayName: "Swift" },
  kotlin: { slug: "kotlin", category: "language", displayName: "Kotlin" },
  dart: { slug: "dart", category: "language", displayName: "Dart" },
  scala: { slug: "scala", category: "language", displayName: "Scala" },
  r: { slug: "r", category: "language", displayName: "R" },
  elixir: { slug: "elixir", category: "language", displayName: "Elixir" },
  lua: { slug: "lua", category: "language", displayName: "Lua" },

  // Frameworks & Runtimes
  nodejs: { slug: "nodedotjs", category: "framework", displayName: "Node.js" },
  node: { slug: "nodedotjs", category: "framework", displayName: "Node.js" },
  "node.js": { slug: "nodedotjs", category: "framework", displayName: "Node.js" },
  react: { slug: "react", category: "framework", displayName: "React" },
  reactjs: { slug: "react", category: "framework", displayName: "React" },
  nextjs: { slug: "nextdotjs", category: "framework", displayName: "Next.js" },
  next: { slug: "nextdotjs", category: "framework", displayName: "Next.js" },
  "next.js": { slug: "nextdotjs", category: "framework", displayName: "Next.js" },
  vue: { slug: "vuedotjs", category: "framework", displayName: "Vue.js" },
  vuejs: { slug: "vuedotjs", category: "framework", displayName: "Vue.js" },
  angular: { slug: "angular", category: "framework", displayName: "Angular" },
  angularjs: { slug: "angular", category: "framework", displayName: "Angular" },
  svelte: { slug: "svelte", category: "framework", displayName: "Svelte" },
  sveltekit: { slug: "svelte", category: "framework", displayName: "SvelteKit" },
  express: { slug: "express", category: "framework", displayName: "Express" },
  fastify: { slug: "fastify", category: "framework", displayName: "Fastify" },
  nestjs: { slug: "nestjs", category: "framework", displayName: "NestJS" },
  django: { slug: "django", category: "framework", displayName: "Django" },
  fastapi: { slug: "fastapi", category: "framework", displayName: "FastAPI" },
  flask: { slug: "flask", category: "framework", displayName: "Flask" },
  laravel: { slug: "laravel", category: "framework", displayName: "Laravel" },
  spring: { slug: "spring", category: "framework", displayName: "Spring Boot" },
  springboot: { slug: "spring", category: "framework", displayName: "Spring Boot" },
  rails: { slug: "ruby-on-rails", category: "framework", displayName: "Ruby on Rails" },
  tailwindcss: { slug: "tailwindcss", category: "framework", displayName: "Tailwind CSS" },
  tailwind: { slug: "tailwindcss", category: "framework", displayName: "Tailwind CSS" },

  // Databases & Storage
  postgresql: { slug: "postgresql", category: "database", displayName: "PostgreSQL" },
  postgres: { slug: "postgresql", category: "database", displayName: "PostgreSQL" },
  psql: { slug: "postgresql", category: "database", displayName: "PostgreSQL" },
  pg: { slug: "postgresql", category: "database", displayName: "PostgreSQL" },
  mysql: { slug: "mysql", category: "database", displayName: "MySQL" },
  redis: { slug: "redis", category: "database", displayName: "Redis" },
  mongodb: { slug: "mongodb", category: "database", displayName: "MongoDB" },
  mongo: { slug: "mongodb", category: "database", displayName: "MongoDB" },
  sqlite: { slug: "sqlite", category: "database", displayName: "SQLite" },
  supabase: { slug: "supabase", category: "database", displayName: "Supabase" },
  prisma: { slug: "prisma", category: "database", displayName: "Prisma" },
  drizzle: { slug: "drizzle", category: "database", displayName: "Drizzle ORM" },
  clickhouse: { slug: "clickhouse", category: "database", displayName: "ClickHouse" },
  elasticsearch: { slug: "elasticsearch", category: "database", displayName: "Elasticsearch" },
  cassandra: { slug: "cassandra", category: "database", displayName: "Cassandra" },
  neo4j: { slug: "neo4j", category: "database", displayName: "Neo4j" },
  mariadb: { slug: "mariadb", category: "database", displayName: "MariaDB" },

  // Cloud & Infrastructure
  aws: { slug: "aws", category: "cloud", displayName: "AWS" },
  amazon: { slug: "aws", category: "cloud", displayName: "AWS" },
  "amazon web services": { slug: "aws", category: "cloud", displayName: "AWS" },
  s3: { slug: "aws", category: "cloud", displayName: "Amazon S3" },
  ec2: { slug: "aws", category: "cloud", displayName: "Amazon EC2" },
  gcp: { slug: "googlecloud", category: "cloud", displayName: "Google Cloud" },
  "google cloud": { slug: "googlecloud", category: "cloud", displayName: "Google Cloud" },
  azure: { slug: "azure", category: "cloud", displayName: "Microsoft Azure" },
  "microsoft azure": { slug: "azure", category: "cloud", displayName: "Microsoft Azure" },
  docker: { slug: "docker", category: "cloud", displayName: "Docker" },
  container: { slug: "docker", category: "cloud", displayName: "Container" },
  kubernetes: { slug: "kubernetes", category: "cloud", displayName: "Kubernetes" },
  k8s: { slug: "kubernetes", category: "cloud", displayName: "Kubernetes" },
  cloudflare: { slug: "cloudflare", category: "cloud", displayName: "Cloudflare" },
  vercel: { slug: "vercel", category: "cloud", displayName: "Vercel" },
  terraform: { slug: "terraform", category: "cloud", displayName: "Terraform" },
  linux: { slug: "linux", category: "cloud", displayName: "Linux" },
  ubuntu: { slug: "ubuntu", category: "cloud", displayName: "Ubuntu" },
  nginx: { slug: "nginx", category: "cloud", displayName: "Nginx" },
  caddy: { slug: "caddy", category: "cloud", displayName: "Caddy" },
  grafana: { slug: "grafana", category: "cloud", displayName: "Grafana" },
  prometheus: { slug: "prometheus", category: "cloud", displayName: "Prometheus" },

  // Developer Tools & Version Control
  github: { slug: "github", category: "devtool", displayName: "GitHub" },
  gh: { slug: "github", category: "devtool", displayName: "GitHub" },
  gitlab: { slug: "gitlab", category: "devtool", displayName: "GitLab" },
  git: { slug: "git", category: "devtool", displayName: "Git" },
  npm: { slug: "npm", category: "devtool", displayName: "NPM" },
  bun: { slug: "bun", category: "devtool", displayName: "Bun" },
  vite: { slug: "vite", category: "devtool", displayName: "Vite" },
  turborepo: { slug: "turborepo", category: "devtool", displayName: "Turborepo" },
  postman: { slug: "postman", category: "devtool", displayName: "Postman" },
  sentry: { slug: "sentry", category: "devtool", displayName: "Sentry" },
  datadog: { slug: "datadog", category: "devtool", displayName: "Datadog" },
  linear: { slug: "linear", category: "devtool", displayName: "Linear" },
  notion: { slug: "notion", category: "devtool", displayName: "Notion" },

  // SaaS, Email & Payments
  stripe: { slug: "stripe", category: "saas", displayName: "Stripe" },
  resend: { slug: "resend", category: "saas", displayName: "Resend" },
  sendgrid: { slug: "sendgrid-badge", category: "saas", displayName: "SendGrid" },
  postmark: { slug: "postmark", category: "saas", displayName: "Postmark" },
  mailgun: { slug: "mailgun", category: "saas", displayName: "Mailgun" },
  twilio: { slug: "twilio", category: "saas", displayName: "Twilio" },
  openai: { slug: "openai", category: "saas", displayName: "OpenAI" },
  chatgpt: { slug: "openai", category: "saas", displayName: "OpenAI" },
  anthropic: { slug: "anthropic", category: "saas", displayName: "Anthropic" },
  slack: { slug: "slack", category: "saas", displayName: "Slack" },
  discord: { slug: "discord", category: "saas", displayName: "Discord" },

  // Protocols & Web
  graphql: { slug: "graphql", category: "protocol", displayName: "GraphQL" },
  gql: { slug: "graphql", category: "protocol", displayName: "GraphQL" },
  html5: { slug: "html5", category: "protocol", displayName: "HTML5" },
  html: { slug: "html5", category: "protocol", displayName: "HTML5" },
  css3: { slug: "css3", category: "protocol", displayName: "CSS3" },
  css: { slug: "css3", category: "protocol", displayName: "CSS3" },
  webassembly: { slug: "webassembly", category: "protocol", displayName: "WebAssembly" },
  wasm: { slug: "webassembly", category: "protocol", displayName: "WebAssembly" },
};
